apiVersion: apps/v1
kind: Deployment
metadata:
  name: multithread-deployment
  namespace: producao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multithread-react
  template:
    metadata:
      labels:
        app: multithread-react
      annotations:
        kubectl.io/restartedAt: 2026-08-03T21:06:50.7189462-03:00
    spec:
      containers:
        - name: multithread-container
          image: keyssong/react-multithread:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5173
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
