apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
  labels:
    app.kubernetes.io/name: rabbitmq
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: producao
  source:
    repoURL: https://github.com/KeyssonG/k8s-gitops.git
    path: rabbitmq/manifests
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
